
CREATE TABLE usuarios (
  id_usuario INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(60) NOT NULL,
  identificacion VARCHAR(20) UNIQUE NOT NULL,
  correo VARCHAR(60) UNIQUE NOT NULL,
  telefono VARCHAR(20) UNIQUE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CHECK (CHAR_LENGTH(nombre) > 3),
  CHECK (correo LIKE '%@%')
);

CREATE TABLE libros (
  id_libro INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  titulo VARCHAR(500) NOT NULL,
  isbn VARCHAR(50) UNIQUE NOT NULL,
  año_publicacion INT NOT NULL,
  autor VARCHAR(60) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CHECK (año_publicacion BETWEEN 1500 AND 2025)
);

CREATE TABLE estados (
  id_estado INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nombre_estado VARCHAR(30) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE prestamos (
  id_prestamo INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  id_usuario INT,
  id_libro INT,
  id_estado INT,
  fecha_prestamo DATE,
  fecha_devolucion DATE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (id_libro) REFERENCES libros(id_libro) ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (id_estado) REFERENCES estados(id_estado) 
);